"""
AVAGuard Desktop Core Interfaces
Defines Protocol-based stable interfaces to allow dynamic hot-swapping of subsystems
and prepare the scanning architecture for future SaaS deployment.
"""

from typing import Dict, Any, List, Optional, Protocol, runtime_checkable

@runtime_checkable
class CompressionStrategyProtocol(Protocol):
    """Protocol for pluggable compression strategies."""
    def compress(self, data: bytes) -> bytes: ...
    def decompress(self, data: bytes) -> bytes: ...
    def algorithm_id(self) -> str: ...


@runtime_checkable
class EncryptionStrategyProtocol(Protocol):
    """Protocol for pluggable encryption strategies."""
    def encrypt(self, data: bytes) -> bytes: ...
    def decrypt(self, data: bytes) -> bytes: ...


@runtime_checkable
class EvidenceStoreProtocol(Protocol):
    """Protocol for the compliant local evidence storage engine."""
    def store_evidence(self, scan_id: str, check_id: str, payload: Dict[str, Any], 
                       classification: str, retention_days: int = 90) -> str: ...
    def retrieve_evidence(self, record_id: str) -> Dict[str, Any]: ...
    def prune_expired(self, batch_size: int = 100) -> int: ...
    def rotate_keys(self, old_version: str, new_version: str, batch_size: int = 50) -> bool: ...
    def close(self) -> None: ...


@runtime_checkable
class TelemetryProtocol(Protocol):
    """Protocol for the operational profiling and metrics collector."""
    def context(self, name: str, **metadata): ...
    def record_event(self, event_name: str, details: Optional[Dict[str, Any]] = None) -> None: ...
    def set_gauge(self, name: str, value: float) -> None: ...
    def record_histogram(self, name: str, value: float) -> None: ...


@runtime_checkable
class QueueManagerProtocol(Protocol):
    """Protocol for the prioritized scan queue orchestrator."""
    def enqueue(self, item: Any) -> None: ...
    def dequeue(self, provider_id: str) -> Optional[Any]: ...
    def record_success(self, provider_id: str, check_duration_ms: float) -> None: ...
    def record_throttle(self, provider_id: str, retry_after_s: float = 0.0) -> None: ...
    def record_error(self, provider_id: str) -> None: ...
    def size(self) -> int: ...
    def clear(self) -> None: ...
    def save_state(self) -> None: ...
    def load_state(self) -> None: ...


@runtime_checkable
class ProviderProtocol(Protocol):
    """Protocol for cloud, OS, or infrastructure scanning providers."""
    def get_capabilities(self) -> Any: ...
    def initialize(self, credentials: Dict[str, Any]) -> None: ...
    def query_resources(self, resource_type: str, fields: List[str] = None) -> Any: ...
    def is_healthy(self) -> bool: ...
