# Generated by Django 6.0.3 on 2026-05-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_policy'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['status'], name='idx_scanresult_status'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['severity'], name='idx_scanresult_severity'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['scan', 'status'], name='idx_scanresult_scan_status'),
        ),
    ]
