# Generated by Django 4.2.30 on 2026-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scanresult_idx_scanresult_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scanresult',
            name='idx_scanresult_severity',
        ),
        migrations.RenameField(
            model_name='scanresult',
            old_name='severity',
            new_name='rule_severity',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='compliance_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='finding_severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='INFO', help_text='Severity of the actual finding outcome (e.g. PASS = INFO).', max_length=20),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='finding_type',
            field=models.CharField(default='compliance_misconfiguration', help_text='e.g., vulnerability, audit', max_length=100),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='List of reference URLs or framework links.'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='rule_severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='MEDIUM', help_text='Severity of the policy/rule itself.', max_length=20),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='scanner_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='source_engine',
            field=models.CharField(default='avaguard-cis-engine', help_text='e.g., avaguard-vuln, custom-policy', max_length=100),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='why_it_matters',
            field=models.TextField(blank=True, help_text='Business impact context for AI and reporting.'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['rule_severity'], name='idx_scanres_rule_sev'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['finding_severity'], name='idx_scanres_finding_sev'),
        ),
    ]
