# Generated by Django 6.0.3 on 2026-05-24 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_scanresult_idx_scanresult_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_settings', serialize=False, to='core.organization')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master toggle for AI features in this organization')),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('mock', 'Mock (Testing)')], default='mock', max_length=50)),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='LLM model to use for generation', max_length=100)),
                ('max_tokens', models.IntegerField(default=1024, help_text='Maximum tokens in LLM response')),
                ('temperature', models.FloatField(default=0.1, help_text='LLM temperature (0.0 = deterministic, 1.0 = creative)')),
                ('top_k_results', models.IntegerField(default=5, help_text='Number of documents to retrieve per query')),
                ('daily_query_limit', models.IntegerField(default=100, help_text='Maximum AI queries per day for this organization')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField(help_text="User's original question")),
                ('sanitized_query', models.TextField(blank=True, help_text='Query after prompt safety processing')),
                ('retrieved_sources', models.JSONField(default=list, help_text='List of {filename, score, snippet} from vector search')),
                ('response_text', models.TextField(blank=True, help_text='LLM-generated answer')),
                ('grounding_score', models.FloatField(blank=True, help_text='How well the answer maps to retrieved sources (0.0-1.0)', null=True)),
                ('model_used', models.CharField(default='mock', help_text='LLM model identifier (e.g. gpt-4o-mini, mock)', max_length=100)),
                ('latency_ms', models.FloatField(default=0.0, help_text='Total request-to-response time in milliseconds')),
                ('retrieval_ms', models.FloatField(default=0.0, help_text='Vector search time only in milliseconds')),
                ('token_count', models.IntegerField(blank=True, help_text='Response token count', null=True)),
                ('flagged', models.BooleanField(default=False, help_text='True if query was flagged by safety checks')),
                ('flag_reason', models.CharField(blank=True, help_text='Reason for safety flag, if any', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_ops_aiqu_user_id_b0fac6_idx'), models.Index(fields=['organization', '-created_at'], name='ai_ops_aiqu_organiz_3d37d0_idx'), models.Index(fields=['flagged'], name='ai_ops_aiqu_flagged_3c1041_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('content_hash', models.CharField(help_text='SHA-256 hash for deduplication', max_length=64)),
                ('word_count', models.IntegerField(default=0)),
                ('source_type', models.CharField(choices=[('cis_benchmark', 'CIS Benchmark'), ('scan_result', 'Scan Result'), ('remediation', 'Remediation Guide'), ('custom', 'Custom Document')], default='custom', max_length=50)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null for global/shared documents', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['-ingested_at'],
                'indexes': [models.Index(fields=['content_hash'], name='ai_ops_know_content_2df349_idx'), models.Index(fields=['source_type'], name='ai_ops_know_source__332417_idx')],
            },
        ),
    ]
