# Generated by Django 6.0.3 on 2026-05-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='llm_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('mock', 'Mock (Testing)')], default='mock', max_length=50),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='model_name',
            field=models.CharField(default='deepseek-chat', help_text='LLM model to use for generation (e.g. deepseek-chat, gpt-4o-mini)', max_length=100),
        ),
    ]
