# Generated by Django 6.0.3 on 2026-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0002_alter_aisettings_llm_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerylog',
            name='is_fallback',
            field=models.BooleanField(default=False, help_text='True if response came from mock/fallback mode instead of real LLM'),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='provider_used',
            field=models.CharField(blank=True, default='', help_text='LLM provider that handled this request (deepseek, openai, mock)', max_length=50),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='source_count',
            field=models.IntegerField(default=0, help_text='Number of documents retrieved for this query'),
        ),
    ]
