# Generated by Django 6.0.3 on 2026-05-30 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0003_aiquerylog_is_fallback_aiquerylog_provider_used_and_more'),
        ('core', '0009_scanresult_idx_scanresult_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='chunks_retrieved',
            field=models.IntegerField(blank=True, help_text='how many FAISS results', null=True),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Full error message if status is error', null=True),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='mode',
            field=models.CharField(default='ai', help_text="'ai' or 'mock'", max_length=10),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='latency in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='status',
            field=models.CharField(default='success', help_text="'success' or 'error'", max_length=20),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['status'], name='ai_ops_aiqu_status_642d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['mode'], name='ai_ops_aiqu_mode_8d3b63_idx'),
        ),
        migrations.AddField(
            model_name='aiqueryfeedback',
            name='query_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_ops.aiquerylog'),
        ),
        migrations.AddField(
            model_name='aiqueryfeedback',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
