# Generated by Django 6.0.3 on 2026-05-31 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0004_aiqueryfeedback_aiquerylog_chunks_retrieved_and_more'),
        ('core', '0009_scanresult_idx_scanresult_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerylog',
            name='average_similarity_score',
            field=models.FloatField(blank=True, help_text='Average reranker score across returned chunks', null=True),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='confidence_level',
            field=models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('none', 'none')], default='none', help_text='Confidence level based on reranker scores', max_length=10),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='rerank_latency_ms',
            field=models.FloatField(blank=True, help_text='Cross-encoder reranking time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='reranker_scores',
            field=models.JSONField(blank=True, default=list, help_text='Per-chunk reranker details: [{filename, hybrid_rank, reranker_score, final_rank}]'),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='retrieval_method',
            field=models.CharField(default='hybrid', help_text="'hybrid', 'bm25', 'faiss_only', 'mock'", max_length=20),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='retrieved_document_count',
            field=models.IntegerField(default=0, help_text='Number of chunks that passed the relevance threshold'),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='top_similarity_score',
            field=models.FloatField(blank=True, help_text='Highest reranker score among returned chunks', null=True),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['confidence_level'], name='ai_ops_aiqu_confide_a6eaf1_idx'),
        ),
    ]
