# Generated by Django 4.2.29 on 2026-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0005_aiquerylog_average_similarity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiqueryfeedback',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
