# Generated by Django 4.2.30 on 2026-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0006_aiqueryfeedback_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerylog',
            name='context_reference',
            field=models.CharField(blank=True, help_text='ID or reference of the ScanResult/Finding', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='transformation_metadata',
            field=models.JSONField(blank=True, default=list, help_text="Audit log of topological transformations (e.g., {'10.0.0.1': '[INTERNAL_HOST]'})"),
        ),
    ]
